version: "3"
services:
  app:
    image: todo_app
    network_mode: "host"
    depends_on:
      - api
    ports:
      - "8080:8080"
  api:
    image: todo_api
    network_mode: "host"
    ports:
      - "5000:5000"
