-- CREATE DATABASE todo;
CREATE SCHEMA todo;
CREATE USER x WITH PASSWORD 'todo';
ALTER USER x WITH SUPERUSER;
-- GRANT ALL ON DATABASE todo TO x;
-- GRANT ALL ON schema todo TO x;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA todo TO x;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA todo TO x;

  CREATE TABLE todo.list (
    id SMALLINT NOT NULL,
    name VARCHAR(256) NOT NULL,
    completed BOOLEAN NOT NULL,
    PRIMARY KEY (id)
  );
